### ISSUE TITLE
Build docker villa í config.yaml

### ISSUE THREAD

**Issue by jonakaren** [hgop/syllabus-2021#21]
Erum í vandræðum með að builda docker í config.yaml með circle.ci
Fáum þessa villu þegar við reynum að setta working directory

![image](https://user-images.githubusercontent.com/70695859/143484998-63fea9d4-8bbe-47ee-8964-d2e74f1f0140.png)

**Comment by ironpeak** [comment]
prófaðu að keyra þetta command í rótinni á repo-inu þínu og sjáðu hvort þetta gerist líka locally

**Comment by jonakaren** [comment]
Það virkaði ekki hjá okkur að keyra commandið svona í terminal, fengum þessa villu:

<img width="737" alt="Screenshot 2021-11-26 at 11 29 56" src="https://user-images.githubusercontent.com/70695859/143574443-bee1a01a-595e-466a-9c03-05957d7ed766.png">

en  'docker build -t connect4-client ./src/connect4-client' virkar. 
En það virkar samt ekki þegar við keyrum það í config.yaml, fáum þessa villu.

<img width="626" alt="Screenshot 2021-11-26 at 11 27 04" src="https://user-images.githubusercontent.com/70695859/143574122-43b5847b-de52-4a38-85ef-0fb34dd48328.png">

**Comment by Arnarps** [comment]
vantar ekki username/connect4-client?

**Comment by jonakaren** [comment]
Eigum við ekki að builda doeckerfileinn í src ekki imageið af dockerhub?

**Comment by kthorri** [comment]
Kannski er betra að gera bara "src/connect4-client" ?

**Comment by kthorri** [comment]
Geturðu copy-paste'að config filenum upp að þessari build skipun hingað?

**Comment by bjorgvin16** [comment]
working_directory og path undir checkout eru parametrar sem við erum búin að vera að fikta í, þeir eru ekki heilagir.

```
version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
    - image: cimg/base:stable
    steps:
    - checkout:
        path: ~/app
    - run: 
        name: Building Docker Image
        command: docker build -t connect4-client ./src/connect4-client
```
