### ISSUE TITLE
no such image

### ISSUE THREAD

**Issue by robertatli** [hgop/syllabus-2021#22]
### config.yml 

```
executors:
  docker-environment:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: koltrax/connect4-client
```
Þegar kemur að build 

```
      - run: 
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
```
Kemur eftirfarandi error:

![image](https://user-images.githubusercontent.com/22518971/143495113-89233b67-8778-4f20-bd91-eb2f58c377b5.png)
Er ég kannski að nota vitlaust image_name eða á það ekki örugglega að vera af docker imageinu mínu, er einnig búinn að prófa "cimg/base", "koltrax/connect4-client:part2", "username/repository" en allt gefur svipaðan error
