### ISSUE TITLE
Build docker image

### ISSUE THREAD

**Issue by Arnarps** [hgop/syllabus-2021#26]
config.yml
```
executors:
  docker-environment:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: arnarp/connect4-client
```

```
jobs:
  build:
    executor: docker-environment
    steps:
    - checkout
    - run:
        name: Build Docker image
        command: docker build -t arnarp/connect4-client ./src/connect4-client/
```

Er að fá þetta error hérna. Er eh skref sem ég gleymdi til að fá docker daemoninn í gang á circleci?
![image](https://user-images.githubusercontent.com/54935919/143580810-adf04464-863e-4587-907b-7c8201fc9ff9.png)

**Comment by kthorri** [comment]
https://github.com/hgop/syllabus-2021/tree/main/assignments/week-01/day-04#build-docker

**Comment by Arnarps** [comment]
```
jobs:
  build:
    executor: docker-environment
    steps:
    - checkout
    - setup_remote_docker # <----- vantaði þetta 
    - run:
        name: Build Docker image
        command: docker build -t arnarp/connect4-client ./src/connect4-client/
```
