### ISSUE TITLE
> SECRET_KEY sem base64

### ISSUE THREAD

**Issue by hauks96** [hgop/syllabus-2021#36]
> Values í secrets þurfa að vera base64 encoded.
> 
> docs: https://kubernetes.io/docs/concepts/configuration/secret/
> 
> Það er eini k8s resource-ið sem þarf base64 encoding (af því sem við notum í verkefninu).

Við gerðum það en bash scriptan setur gæsalappir utanum base64 strenginn.

_Originally posted by @hauks96 in https://github.com/hgop/syllabus-2021/issues/35#issuecomment-981876078_

**Comment by ironpeak** [comment]
Geturu komið með dæmi

**Comment by hauks96** [comment]
Environment í CircleCI
```
CONNECT4_SERVER_SECRET_KEY=dGhyZWVzY29tcGFueQ==
```
Outputtið sem við erum að logga í circleCI pipelineinu.
```
data:
  DATABASE_USERNAME: "*************"
  DATABASE_PASSWORD: "*************"
  SECRET_KEY: "dGhyZWVzY29tcGFueQ"
```

**Comment by ironpeak** [comment]
Er það að valda error?

Hefði haldið að qoutes væru í lagi

**Comment by Valtyrs** [comment]
\"{{${key}}}\"

**Comment by hauks96** [comment]
Liklega == merkin sem eru ad hverfa eftir cut hja okkur

**Comment by ironpeak** [comment]
> sed "s/"{{${key}}}"/${value}/g" ef þetta er too much info þa ma remove þetta

Sé að " eru að bætast við þarna í kringum {{${key}}}, en held að " í kringum values séu í lagi

**Comment by Valtyrs** [comment]
átti að koma \" fyrir fram og eftir {{$key}} en git tók það burt

**Comment by hauks96** [comment]
SECRET_KEY er núna rétt Base64 encoded en virkar ennþá ekki
```
apiVersion: v1
kind: Secret
metadata:
  name: connect4-server
  labels:
    app: connect4-server
data:
  DATABASE_USERNAME: "*************"
  DATABASE_PASSWORD: "*************"
  SECRET_KEY: "********************"
```
ERROR:
```
Error from server (BadRequest): error when creating "connect4-server.yaml":
Secret in version "v1" cannot be handled as a Secret: v1.Secret.Data: decode base64: 
illegal base64 data at input byte 12, error found in #10 byte of ...|escompany","DATABASE|..., bigger context ...|":
"v1","data": {"DATABASE_PASSWORD":"*************","DATABASE_USERNAME":"*************","SECRET_KEY":|...
```
