### ISSUE TITLE
SSL Verify issue on acceptance tests

### ISSUE THREAD

**Issue by hauks96** [hgop/syllabus-2021#49]
The acceptance tests run fine locally with the server running on localhost:5000. After deployment, the acceptance test is triggered and fails to request the resource because of an SSL verification issue.

This is the circle-ci error on the acceptance-test:
```py
raise SSLError(e, request=request)
requests.exceptions.SSLError: 
HTTPSConnectionPool(host='connect4-server.acceptance.threescompany.hgopteam.com', port=443):
Max retries exceeded with url: /status 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
```

I tried to check the URL manually, i.e I went to connect4-server.acceptance.threescompany.hgopteam.com which returns 404 not found, but I am not sure whether that is expected or not.

Furthermore I checked the pods under the namespace acceptance:
```bash
$ kubectl get pods --namespace acceptance
>>
NAME                               READY   STATUS    RESTARTS   AGE
connect4-database-0                1/1     Running   0          91m
connect4-server-5d965d5798-bnph7   1/1     Running   0          12m
connect4-migrations-5f94c          0/1     Error     0          12m
connect4-migrations-q72qb          0/1     Error     0          11m
connect4-migrations-vvtlt          0/1     Error     0          11m
```
As can be seen the server is running just fine, but the migrations are erroring. The logs show that the password is incorrect. I've already tried deleting all the pods in the acceptance namespace and rerunning the pipeline. We have in the project environment variables on circleci already defined CONNECT4_SERVER_DATABASE_PASSWORD and CONNECT4_SERVER_DATABASE_USERNAME, so I am not sure whether it is just prioritizing that one over the one set in the acceptance environment in the yaml file.

```py
$ kubectl logs connect4-migrations-vvtlt -n acceptance
>> Traceback (most recent call last):
...
psycopg2.OperationalError: connection to server at "connect4-database" (10.152.183.123), port 5432 failed: FATAL:  password authentication failed for user "connect4"
```

What to do?

**Comment by hauks96** [comment]
This is the generated ingress in circle-ci
```
apiVersion: v1
kind: Secret
metadata:
  name: connect4-server
  labels:
    app: connect4-server
data:
  DATABASE_USERNAME: Y29ubmVjdDQ=
  DATABASE_PASSWORD: Y29ubmVjdDQ=
  SECRET_KEY: ********************
```

**Comment by hauks96** [comment]
UPDATE:
I have resolved the SSL verification issue. **However I'm still dealing with the migration problem.**

To solve the SSL Issue, I had to do the following.
1. Replace the "host" parameters in the ingress template with {{HOST}} in the server k8
    ```yaml
    spec:
      tls:
      - hosts:
        - {{HOST}}
        secretName: connect4-server-tls
      rules:
      - host: {{HOST}}
        ...
    ```
2. Add the CONNECT4_SERVER_HOST environment variable to the deployment stage in the circleci yaml file.\
I created a new executor for the deployment stage and it now looks like this
    ```yaml
      deployment-environment:
        docker:
          - image: circleci/buildpack-deps:stretch
        environment:
          CONNECT4_SERVER_HOST: connect4-server.threescompany.hgopteam.com
       ...
       deploy:
          executor: deployment-environment
          steps:
             ....
    ```

3. I also added some ngnix annotations to the server k8 ingress template yesterday which you might have to do.
    I added this because I always got CORS errors when trying to play the game on our website.
    ```yaml
      ...
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
      ...
    ```
